INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, TASTED) VALUES (1, 'Chouffe', 'Yellow', false);
INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, TASTED) VALUES (2, 'Chimay', 'Amber', false);
INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, TASTED) VALUES (3, 'Kwack', 'Amber', false);
INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, TASTED) VALUES (4, 'Ch''ti Triple','Yellow', false);
INSERT INTO BEER_TABLE (ID, BEER_NAME, BEER_COLOR, TASTED) VALUES (5, 'Goudale', 'Amber', false);