version: '3.6'
services:
  mariadb:
    image: mariadb:10.3
    command: [ "mysqld", "--lower_case_table_names=1", "--character-set-server=utf8", "--innodb-flush-method=fsync" ]
    hostname: mariadb
    environment:
      - MYSQL_DATABASE=apero
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mariadb/data:/var/lib/mysql
      - ./init/script:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "mariadb"]
#      timeout: 20s
#      retries: 10
    networks:
      - default
networks:
  default: {}
